# Site settings
name: frozenrain yoo
email: frozenrain.yoo@gmail.com
author: frozenrainyoo
url: https://frozenrainyoo.github.io/
resume_site: https://frozenrainyoo.github.io/
github: https://github.com/frozenrainyoo
baseurl: ""
description: 기술 블로그
meta_description:
motto:
banner:
disqus_url: https://https-frozenrainyoo-github-io.disqus.com
disqus_id: frozen_rain
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: frozenrainyoo

# Build settings
markdown: kramdown

